name: deployment

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        
      - name: Run Tests
        run: mvn -B test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t parking-lot-image .
          docker tag parking-lot-image ${{ secrets.DOCKER_USERNAME }}/parking-lot-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/parking-lot-image:latest
